<a href="https://colab.research.google.com/github/k2moon/ml-hg/blob/main/hg_05_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 트리의 앙상블
---


## 핵심 키워드
---
- 앙상블 학습
- 랜덤 포레스트
- 엑스트라 트리
- 그레이던트 부스팅

<table align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/rickiepark/hg-mldl/blob/master/5-3.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />구글 코랩에서 실행하기</a>
  </td>
</table>

## 앙상블 학습 ensemble learning
---
- 더 좋은 예측 결과를 만들기 위해 여러개의 모델을 훈련하는 머신러닝 알고리즘
- 정형 데이터 structured data 에서 띄어난 성과를 보임
- 비정형 데이터 structured data는 신경망 알고리즘 사용

## 랜덤 포레스트 Random Forest
---
- 대표적인 결정 트리 기반의 앙상블 학습 방법
- 여러 개의 결정 트리(Decision Tree)를 결합하여 하나의 결정 트리보다 더 좋은 성능을 내는 머신러닝 기법
- 여러 개의 약 분류기 (Weak Classifier)를 결합하여 강 분류기(Strong Classifier)를 만드는 것
- 부트스트랩 샘플을 사용하고 랜덤하게 일부 특성을 선택하여 트리를 만드는 것이 특징
- 사이킷런의 랜덤 포레스트는 기본적으로 100개의 결정 트리 사용
- 결과를 모아 다수결 투표나 평균으로 최종 결과 결정
- 참고 사이트 : https://tinyurl.com/3aawud7s
- 참고 사이트 : https://tinyurl.com/58vn6mj9
- 참고 사이트 : https://tinyurl.com/yad46zrc

![](https://www.tibco.com/sites/tibco/files/media_entity/2021-05/random-forest-diagram.svg)

### 부트스트랩 샘플 bootstrap sample
---
- 데이터 세트에서 중복을 허용하여 데이터를 샘플링 하는 방식
- 기본적으로 부트스틀랩 샘플은 훈련세트의 크기와 같게 만듬
- 부트스트랩 샘플을 가지고 결정트리 생성 
- 그 이후 배깅 Bagging 과 부스팅 Boosting  방법을 이용 랜덤 포레스트 Random Forest가 만들어 짐
- 나무를 모으는 방법이 배깅과 부스팅

![](https://t1.daumcdn.net/cfile/tistory/993C9C505A92751109)

### 배깅 Bagging 
---
- **B**ootstrap **Agg**regat**ing** 준말
- 부트스트랩 Bootstrap 샘플링을 이용하여 주어진 하나의 데이터로 학습된 예측 모델 보다 더 좋은 모델을 만들 수 있는 앙상블 기법
- 샘플을 여러 번 뽑아(Bootstrap) 각 모델을 학습시켜 결과물을 집계(Aggregration)하는 방법
- Categorical Data는 투표 방식(Votinig)으로 결과를 집계하며, Continuous Data는 평균으로 집계

![Bagging](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fb4wG8O%2FbtqyfYW98AS%2FYZBtUJy3jZLyuik1R0aGNk%2Fimg.png)

### 부스팅 Boosting
---
- 부스팅은 가중치를 활용하여 약 분류기를 강 분류기로 만드는 방법
- 배깅이 독립적인 결정 트리가 각각 값을 예측한 뒤, 그 결과 값을 집계해 최종 결과 값을 예측하는 방식이라면 부스팅은 모델 간 팀워크
- 처음 모델이 예측을 하면 그 예측 결과에 따라 데이터에 가중치가 부여
- 분류가 잘못된 데이터에 가중치를 부여해주는 이유는 다음 모델에서 더 집중해 분류하기 위함
- 부여된 가중치가 다음 모델에 영향을 줌
- 잘못 분류된 데이터에 집중하여 새로운 분류 규칙을 만드는 단계를 반복
- 참고 사이트 : https://tinyurl.com/yad46zrc


**부스팅 Boosting : + -로 구성된 데이터 셋 분류 문제**

![Boosting](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FkCejr%2FbtqyghvqEZB%2F9o3rKTEsuSIDHEfelYFJlk%2Fimg.png)

**D1 Part**
-  2/5 지점을 횡단
- 위쪽의 +는 잘못 분류가 되었고, 아래쪽의 두 -도 잘못 분류
- 잘못 분류가 된 데이터는 가중치를 높여주고, 잘 분류된 데이터는 가중치를 낮추어 줌 

**D2 Part**
-  D1에서 잘 분류된 데이터는 크기 작아 짐 => 가중치 낮아짐
- 위쪽의 +는 잘못 분류가 되었고, 아래쪽의 두 -도 잘못 분류
- 잘못 분류된 +는 커짐 => 가중치 커짐
- D2에서는 오른쪽 세 개의 -가 잘못 분류

**D3 Part**
- 세 개의 -의 가중치가 커졌음
- 맨 처음 모델에서 가중치를 부여한 +와 -는 D2에서는 잘 분류가 되었기 때문에 D3에서는 가중치가 다시 작아짐

**Combined classifier**
- D1, D2, D3의 Classifier를 합쳐 최종 Classifier를 구할 수 있습니다. 최종 Classfier는 +와 -를 정확하게 구분

### 의사 결정 트리와 랜덤 포레스트의 차이점
---
- 랜덤 포레스트는 의사 결정 트리의 그룹
- 의사 결정 트리는 의사 결정에 사용하는 규칙을 만드는 경향
- 랜덤 포레스트는 기능을 무작위로 선택하고 관찰하여 의사 결정 트리의 포리스트를 만든 다음 결과를 평균화
- 이론에 따르면 많은 수의 상관되지 않은 트리가 하나의 개별 의사 결정 트리보다 더 정확한 예측을 생성
- 이는 많은 트리들이 함께 작동하여 개별 오류와 과적합으로부터 서로를 보호하기 때문


### 랜덤 포레스트 알고리즘은 비즈니스에서 어떻게 사용됩니까?
---
> 랜덤 포레스트는 비즈니스 환경에서 많이 응용됩니다. 예를 들어, 단일 의사 결정 트리에서는 와인과 관련된 데이터 세트를 분류하여 다양한 와인을 농도가 연한 와인 또는 농도가 진한 와인으로 구분할 수 있습니다.

> 랜덤 포레스트는 많은 트리를 생성하므로 최종 결과 예측을 훨씬 더 정교하게 합니다. 가격, 탄닌, 산도, 알코올 함량, 설탕, 가용성 및 다양한 기타 모든 기능을 비교하여 와인과 여러 트리를 가질 수 있습니다. 그런 다음 결과를 평균화하여 수많은 기준을 기반으로 하여 전반적으로 (거의 틀림없이) 최고의 와인을 예측할 수 있습니다.

> 비즈니스에서 랜덤 포레스트 알고리즘은 입력 데이터 범위가 다양하고 상황이 복잡한 시나리오에서 사용할 수 있습니다. 고객이 회사를 떠날 시기를 식별하는 것을 예로 들겠습니다. 고객 이탈은 복잡하며 일반적으로 제품 비용, 최종 제품에 대한 만족도, 고객 지원 효율성, 지불 용이성, 계약 기간, 제공되는 추가 기능, 성별, 연령, 위치 등 많은 요소를 포함합니다. 랜덤 포레스트 알고리즘은 이러한 모든 요소에 대한 의사 결정 트리를 생성하여 조직의 고객 중 이탈 위험이 높은 고객을 정확하게 예측할 수 있습니다.

> 또 다른 복잡한 예는 어떤 고객이 한 해에 가장 많은 지출을 할 것인지 예측하는 것입니다. 마케팅 부서는 종합적인 변수와 속성을 분석하여 그 해에 누구를 목표로 삼아야 하는지에 대해 예측을 할 수 있습니다.

참고 사이트 : https://www.tibco.com/ko/reference-center/what-is-a-random-forest

### 배깅과 부스팅 차이 
---
> 배깅
> 병렬로 학습
> 

> 부스팅
> 순차적으로 학습
> 한번 학습이 끝난 후 결과에 따라 가중치를 부여
> 오답에 대해서는 높은 가중치를 부여
> 오답을 정답으로 맞추기 위해 오답에 더 집중
> 속도가 느리고 오버 피팅이 될 가능성 높음

> 개별 결정 트리의 낮은 성능이 문제라면 부스팅이 적합하고, 오버 피팅이 문제라면 배깅이 적합

![배깅과 부스팅 차이](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fbwr6JW%2FbtqygiHRbRk%2Fcy5hbDAPpTjCG7xa6UWxi0%2Fimg.png)

---

In [1]:
# 데이터 준비
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

wine = pd.read_csv('https://bit.ly/wine_csv_data')

data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()

train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)

In [3]:
# 교차 검증 수행, 기본 100개 결정 트리
# return_train_score=True : 검증 점수 뿐만 아니라 훈련 세트에 대한 점수도 반환
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(rf, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9973541965122431 0.8905151032797809


- 과대적합
- RandomForestClassifier클래스는 교차 검증 수행 시 기본 100개 결정 트리
- return_train_score=True : 검증 점수 뿐만 아니라 훈련 세트에 대한 점수도 반환

In [10]:
rf2 = RandomForestClassifier(n_jobs=-1, random_state=42, max_depth=5)
scores = cross_validate(rf2, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.8696363615536095 0.8608834308136523


In [4]:
# 특성 중요도 확인 
rf.fit(train_input, train_target)
print(rf.feature_importances_)

[0.23167441 0.50039841 0.26792718]


- 결정 트리 모델의 특성 중요도 : [ 0.12345626 0.86862934 0.0079144 ]
- 당도의 중요도는 감소하고 알코올 도수와 pH특성의 중요도 상승
- 랜덤 포레스트가 특성의 일부를 랜덤하게 선택하여 결정 트리를 훈련하기 때문
- 랜덤 포레스트는 과대적합을 줄이고 일반화 성능을 높이는 데 도움이 됨

In [5]:
# oob_score Out Of Bag
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)

rf.fit(train_input, train_target)
print(rf.oob_score_)

0.8934000384837406


- OOB Out Of Bag 부트스트랩 샘플에 포함되지 않고 남은 샘플
- oob_score=True OOB로 평가, 검증 세트 처럼 사용 가능
- 교차 검증의 테스트 세트와 비슷한 결과

## 엑스트라 트리 Extra Tree
---
- 결정트리가 제공하는 대분의 매개변수 제공
- 부트스트랩 샘플을 사용 하지 않고 전체 훈련 세트 사용
- 대신 노드를 분할 할때 가장 좋은 분할을 찾는 것이 아니라 무작위 분할
- DecisionTreeClassifier의 splitter='random' 결정 트리 사용
- 무작위 분활이라 성능이 낮아지겠지만 많은 트리를 앙상블하기 때문에 과대적합을 막고 검증 세트의 점수를 높이는 효과
- 특성이 많으면 최적의 분할을 찾는 것은 시간이 많이 걸림
- 무작위 분할은 특성이 많을 때 빠른 트리 구성이 가능
- 보통 엑스트라 트리가 더 많은 결정 트리를 훈련 해야함, 기본 100개 

In [12]:
from sklearn.ensemble import ExtraTreesClassifier

et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9974503966084433 0.8887848893166506


- 특성이 많지 않아 랜덤포레스트와 비슷한 결과 나옴 

In [13]:
# 특성 중요도 확인
et.fit(train_input, train_target)
print(et.feature_importances_)

[0.20183568 0.52242907 0.27573525]


## 그레이디언트 부스팅 Gradient boosting
---
- 깊이가 얕은 결정 트리 사용하여 오차를 보완하는 방식의 앙상블 방법
- 사이킷런의 GradientBoostingClassifier 클래스는 기본적으로 깊이 3 결정트리 100개 사용
- 깊이가 얕아 과대 적합에 강하고 일반화 성능 기대
- 그레이디언트 경사 하강법을 사용하여 트리를 앙상블에 추가
- 분류에서는 로지스틱 손실 함수, 회구에서는 평균 제곱 오차를 사용
- 학습율 매개변수로 속도 조절

In [14]:
# GradientBoostingClassifier로 교차 검증
# 기본 깊이 3, 결정 트리 100개, 학습률 0.1
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(random_state=42)
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.8881086892152563 0.8720430147331015


In [15]:
# 앙상블에 추가될 결정 트리 갯수와 학습률 늘려서 확인
gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, random_state=42)
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9464595437171814 0.8780082549788999


- 트리의 갯수를 늘려도 과대적합에 강함

In [ ]:
# 특성 중요도 확인 `feature_importances_`
gb.fit(train_input, train_target)
print(gb.feature_importances_)

[0.15872278 0.68010884 0.16116839]


- 랜덤포레스트 보다 일부 특성 당도에 더 집중된 모습 

## 히스토그램 기반 부스팅 Histogram-based Gredient Boosting
---
- 정형 데이터를 다루는 머신러닝 알고리즘 중 인기가 높은 알고리즘
- 그레이디언트 부스팅의 속도와 성능을 개선한 것
- 사이킷런 HistGradientBoosting
- 그외 XGBoost,LightGBM 이 있음

### 사이킷런 HistGradientBoostingClassifier
---
- 사이킷런 버전에 주의
-  특성 중요도를 계산하기 위해서 permutation_importance() 메소드를 사용
- n_repeats는 랜덤하게 섞을 횟수를 의미, 기본값은 5
- importances_mean에 접근하면 특성 중요도의 평균

In [16]:
# 사이킷런 1.0 버전 아래에서는 다음 라인의 주석을 해제하고 실행하세요.
# from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier

hgb = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9321723946453317 0.8801241948619236


- 결과적으로 수치를 보면 과대 적합을 잘 억제하면서 그레이디언트 부스팅보다 높은 효과

In [17]:
# 특성 중요도 확인
from sklearn.inspection import permutation_importance

hgb.fit(train_input, train_target)
result = permutation_importance(hgb, train_input, train_target, n_repeats=10,
                                random_state=42, n_jobs=-1)
print(result.importances_mean)

[0.08876275 0.23438522 0.08027708]


- 이 함수는 특성을 하나씩 랜덤하게 섞어서 모델의 성능이 변화하는지를 관찰하고, 어떤 특성이 중요한지 계산
- 매개변수 n_repeats는 랜덤하게 섞을 횟수를 의미하는데, 기본값은 5
- importances_mean에 접근하면 특성 중요도의 평균갑 

In [18]:
# 테스트 세트에서 특성 중요도 확인
result = permutation_importance(hgb, test_input, test_target, n_repeats=10,
                                random_state=42, n_jobs=-1)
print(result.importances_mean)

[0.05969231 0.20238462 0.049     ]


- 결과를 보면 그레이디언트 부스팅과 비슷하게 당도에 조금 더 집중
- 이런 분석을 통해 모델이 실전에서 어떤 특성에 관심을 둘지 예상해볼 수 있음

In [21]:
# 최종 성능 확인
hgb.score(test_input, test_target)

0.8723076923076923

### XGBoost
---
- 대표적인 그레이디언트 부스팅 알고리즘
- 사이킷런에서 제공하는 클래스 아님에도 불구하고 cross_validate() 메소드와 함께 사용 가능
- tree_method를 'hist'로 지정하면 히스토그램 기반 그레이디언트 부스팅

In [24]:
from xgboost import XGBClassifier

xgb = XGBClassifier(tree_method='hist', random_state=42)
scores = cross_validate(xgb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.8824322471423747 0.8726214185237284


### LightGBM
---
- 마이크로소프트에서 만든 라이브러리로, 사이킷런의 히스토그램 기반 그레이디언트 부스팅에 큰 영향을 줌
-  사이킷런에서 제공하는 cross_validate() 메소드와 함께 사용 가능
- XGBoost를 사용했을 때보다는 약간의 과대 적합한 경향이 있지만 다른 라이브러리에 비해 잘 억제하고 있음

In [22]:
from lightgbm import LGBMClassifier

lgb = LGBMClassifier(random_state=42)
scores = cross_validate(lgb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9338079582727165 0.8789710890649293
